service: gcf-api # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

custom:
  userTableName: 'users-Table-${self:provider.stage}'
  clientTableName: 'clients-Table-${self:provider.stage}'
  projectTableName: 'projects-Table-${self:provider.stage}'
  notificationTableName: 'notifications-Table-${self:provider.stage}'
  receiptTableName: 'receipts-Table-${self:provider.stage}'
  stageTableName: 'stages-Table-${self:provider.stage}'

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  memorySize: 128
  region: us-east-1
  role: arn:aws:iam::675462175633:role/gcf-role
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn" ] }
        - { "Fn::GetAtt": ["ClientsDynamoDBTable", "Arn" ] }
        - { "Fn::GetAtt": ["ProjectsDynamoDBTable", "Arn" ] }
        - { "Fn::GetAtt": ["StagesDynamoDBTable", "Arn" ] }
        - { "Fn::GetAtt": ["ReceiptsDynamoDBTable", "Arn" ] }
        - { "Fn::GetAtt": ["NotificationsDynamoDBTable", "Arn" ] }
  
  environment:
    USERS_TABLE: ${self:custom.userTableName}
    CLIENTS_TABLE: ${self:custom.clientTableName}
    PROJECTS_TABLE: ${self:custom.projectTableName}
    NOTIFICATIONS_TABLE: ${self:custom.notificationTableName}
    RECEIPTS_TABLE: ${self:custom.receiptTableName}
    STAGES_TABLE: ${self:custom.stageTableName}



functions:
  usersFunction:
    handler: user-handler/handler.handler
    events:
      - http:
          path: users
          method: get
          cors: true

      - http:
          path: users/{username}
          method: get
          cors: true

      - http:
          path: users/login
          method: post
          cors: true
          
      - http:
          path: users
          method: post
          cors: true 

resources:
  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: username
            AttributeType: S
        KeySchema:
          -
            AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
        TableName: ${self:custom.userTableName}

    ClientsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: clientName
            AttributeType: S
        KeySchema:
          -
            AttributeName: clientName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
        TableName: ${self:custom.clientTableName}

    StagesDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: stageName
            AttributeType: S
        KeySchema:
          -
            AttributeName: stageName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
        TableName: ${self:custom.stageTableName}

    ReceiptsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: receiptName
            AttributeType: S
        KeySchema:
          -
            AttributeName: receiptName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
        TableName: ${self:custom.receiptTableName}

    ProjetsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: projectName
            AttributeType: S
        KeySchema:
          -
            AttributeName: projectName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
        TableName: ${self:custom.projectTableName}

    NotificationsDynamoDBTable:
        Type: 'AWS::DynamoDB::Table'
        Properties:
          AttributeDefinitions:
            -
              AttributeName: notificationName
              AttributeType: S
          KeySchema:
            -
              AttributeName: notificationName
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 3
            WriteCapacityUnits: 3
          TableName: ${self:custom.notificationTableName}
